name: Build, Test and Deploy

on: [push, pull_request]

jobs:
  backend:
    name: Backend - Install dependencies & unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Back-End Tests
        working-directory: back
        run: mvn clean install
      - name: Report Back-End Tests
        uses: phoenix-actions/test-reporting@v15
        if: always()
        with:
          name: Backend Tests (JUnit)
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

  frontend:
    name: Frontend - Install dependencies & unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: front
        run: npm ci
      - name: Run Front-End Tests
        working-directory: front
        run: npm run test:ci
      - name: Report Front-End Tests
        uses: phoenix-actions/test-reporting@v15
        if: always()
        with:
          name: Frontend Tests (JUnit)
          path: front/test-results/junit.xml
          reporter: jest-junit

  docker-deploy:
    name: Docker Deploy
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Placeholder for future deployment
        run: echo "Deployment will happen here..."
