name: Build, Test and Deploy

on: [push, pull_request]

jobs:
  backend-test:
    name: Backend unit test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Back-End Tests
        working-directory: back
        run: mvn clean install
      - name: Report Back-End Tests
        uses: phoenix-actions/test-reporting@v15
        if: always()
        with:
          name: Backend Tests (JUnit)
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

  frontend-test:
    name: Frontend unit test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: front
        run: npm ci
      - name: Run Front-End Tests
        working-directory: front
        run: npm run test:ci
      - name: Report Front-End Tests
        uses: phoenix-actions/test-reporting@v15
        if: always()
        with:
          name: Frontend Tests (JUnit)
          path: front/test-results/junit.xml
          reporter: java-junit

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-deploy:
    name: Docker Deploy
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test, sonar-analysis]
    steps:
      - name: Placeholder for future deployment
        run: echo "Deployment will happen here..."
