name: CI

on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: front
        run: npm install
      - name: Run Front-End Tests
        working-directory: front
        run: npm run test:ci

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        working-directory: back
        run: mvn clean install -DskipTests
      - name: Run Back-End Tests
        working-directory: back
        run: mvn test
